-- +goose Up

CREATE TABLE oauth_accounts (
    "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"          BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "provider"         VARCHAR(32) NOT NULL,
    "provider_subject" VARCHAR(255) NOT NULL,
    "provider_email"   VARCHAR(255) NOT NULL,
    "created_at"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT oauth_accounts_provider_subject_unique UNIQUE ("provider", "provider_subject")
);

CREATE INDEX idx_oauth_accounts_user ON oauth_accounts("user_id");

-- +goose Down

DROP TABLE IF EXISTS oauth_accounts;
