-- +goose Up

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_user_id VARCHAR(32) UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    user_id BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    refresh_token_hash VARCHAR(255) NOT NULL,
    device_type VARCHAR(50),
    device_name VARCHAR(255),
    ip_address INET,
    user_agent TEXT,
    logged_in_at TIMESTAMPTZ DEFAULT NOW(),
    last_active_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE TABLE blocked_domains (
    id BIGINT PRIMARY KEY,
    domain VARCHAR(255) UNIQUE NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    original_url TEXT NOT NULL,
    url_hash CHAR(64) NOT NULL UNIQUE
);

    CREATE TABLE urls (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY
            PRIMARY KEY,

        user_id BIGINT NOT NULL
            REFERENCES users(id)
            ON DELETE CASCADE,

        short_code VARCHAR(16) NOT NULL UNIQUE,

        destination_id BIGINT NOT NULL
            REFERENCES destinations(id),

        title VARCHAR(255),
        description TEXT,
        is_custom BOOLEAN DEFAULT FALSE,
        is_safe BOOLEAN DEFAULT TRUE,
        click_count BIGINT DEFAULT 0,
        expires_at TIMESTAMPTZ NULL,
        is_active BOOLEAN DEFAULT TRUE,
        last_accessed_at TIMESTAMPTZ NULL,
        destination_status SMALLINT,
        last_health_check TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW(),
        deleted_at TIMESTAMPTZ NULL
    );

CREATE INDEX idx_urls_shortcode ON urls(short_code);
CREATE INDEX idx_urls_user ON urls(user_id);
CREATE INDEX idx_urls_expiry ON urls(expires_at);

CREATE TABLE url_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    url_id BIGINT NOT NULL
        REFERENCES urls(id)
        ON DELETE CASCADE,

    original_url TEXT NOT NULL,
    version_number INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_url_versions_url ON url_versions(url_id);

CREATE TABLE click_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    url_id BIGINT NOT NULL
        REFERENCES urls(id)
        ON DELETE CASCADE,

    clicked_at TIMESTAMPTZ DEFAULT NOW(),
    ip_address INET,
    country VARCHAR(100),
    city VARCHAR(100),
    browser VARCHAR(100),
    device_type VARCHAR(50),
    referrer TEXT,
    user_agent TEXT
);

CREATE INDEX idx_click_logs_url ON click_logs(url_id);
CREATE INDEX idx_click_logs_date ON click_logs(clicked_at);
CREATE INDEX idx_click_logs_url_date ON click_logs(url_id, clicked_at);

CREATE TABLE daily_url_stats (
    url_id BIGINT NOT NULL
        REFERENCES urls(id)
        ON DELETE CASCADE,
    stat_date DATE NOT NULL,
    total_clicks BIGINT DEFAULT 0,
    PRIMARY KEY (url_id, stat_date)
);

-- +goose Down
DROP TABLE IF EXISTS daily_url_stats;
DROP TABLE IF EXISTS click_logs;
DROP TABLE IF EXISTS url_versions;
DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS destinations;
DROP TABLE IF EXISTS blocked_domains;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
