-- +goose Up

CREATE TABLE users (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
    "email"              VARCHAR(255) NOT NULL UNIQUE,
    "password_hash"      VARCHAR(255) NOT NULL,
    "display_user_id"    VARCHAR(32) UNIQUE,
    "display_user_name"  VARCHAR(255),
    "role"               VARCHAR(20) NOT NULL DEFAULT 'USER',
    "created_at"         TIMESTAMPTZ DEFAULT NOW(),
    "updated_at"         TIMESTAMPTZ DEFAULT NOW(),
    "deleted_at"         TIMESTAMPTZ NULL,
    "password_changed_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE sessions (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"            BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "refresh_token_hash" VARCHAR(255) NOT NULL,
    "device_type"        VARCHAR(50),
    "device_name"        VARCHAR(255),
    "country"            VARCHAR(100),
    "city"               VARCHAR(100),
    "ip_address"         INET,
    "user_agent"         TEXT,
    "logged_in_at"       TIMESTAMPTZ DEFAULT NOW(),
    "last_active_at"     TIMESTAMPTZ DEFAULT NOW(),
    "session_status"     SMALLINT DEFAULT 1,
    "expires_at"         TIMESTAMPTZ,
    "revoked_at"         TIMESTAMPTZ,
    CONSTRAINT "sessions_status_check" CHECK ("session_status" IN (0, 1, 2))
);

CREATE INDEX idx_sessions_user ON sessions("user_id");
CREATE INDEX idx_sessions_expires_at ON sessions("expires_at");
CREATE INDEX idx_sessions_purge ON sessions ("session_status", "last_active_at");
CREATE INDEX idx_sessions_user_lastactive ON sessions ("user_id", "last_active_at" DESC);

CREATE TABLE password_history (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"         BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "password_hash"   VARCHAR(255) NOT NULL,
    "ip_address"      INET,
    "user_agent"      TEXT,
    "created_at"      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_password_history_user ON "password_history"("user_id");
CREATE INDEX idx_password_history_created ON "password_history" ("created_at");

CREATE TABLE blocked_domains (
    "id"        SERIAL PRIMARY KEY,
    "domain"    VARCHAR(255) UNIQUE NOT NULL,
    "reason"    TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE blocked_ip_ranges (
    "id"          BIGSERIAL PRIMARY KEY,
    "cidr"        CIDR NOT NULL,
    "description" TEXT NOT NULL
);

CREATE TABLE destinations (
    "id"                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "original_url"               TEXT NOT NULL,
    "url_hash"                   CHAR(64) NOT NULL UNIQUE,
    "destination_health_status"  SMALLINT,
    "last_health_check"          TIMESTAMPTZ
);

CREATE TABLE urls (
    "id"                          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    "user_id"                     BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "short_code"                  VARCHAR(16) NOT NULL UNIQUE,
    "destination_id"              BIGINT NOT NULL REFERENCES "destinations"("id"),
    "title"                       VARCHAR(255),
    "description"                 TEXT,
    "is_custom"                   BOOLEAN DEFAULT FALSE,
    "is_safe"                     BOOLEAN DEFAULT TRUE,
    "click_count"                 BIGINT DEFAULT 0,
    "expires_at"                  TIMESTAMPTZ NULL,
    "url_status"                  SMALLINT DEFAULT 1,
    "last_accessed_at"            TIMESTAMPTZ NULL,
    "destination_health_status"   SMALLINT DEFAULT 0,
    "last_health_check"           TIMESTAMPTZ,
    "destination_last_http_status" INTEGER NULL,
    "created_at"                  TIMESTAMPTZ DEFAULT NOW(),
    "updated_at"                  TIMESTAMPTZ DEFAULT NOW(),
    "deleted_at"                  TIMESTAMPTZ NULL
);

CREATE INDEX idx_urls_shortcode ON "urls"("short_code");
CREATE INDEX idx_urls_user ON "urls"("user_id");
CREATE INDEX idx_urls_expiry ON "urls"("expires_at");

CREATE TABLE url_versions (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "url_id"          BIGINT NOT NULL REFERENCES "urls"("id") ON DELETE CASCADE,
    "original_url"    TEXT NOT NULL,
    "version_number"  INTEGER NOT NULL,
    "created_at"      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_url_versions_url ON "url_versions"("url_id");

CREATE TABLE click_logs (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "url_id"      BIGINT NOT NULL REFERENCES "urls"("id") ON DELETE CASCADE,
    "clicked_at"  TIMESTAMPTZ DEFAULT NOW(),
    "ip_address"  INET,
    "country"     VARCHAR(100),
    "city"        VARCHAR(100),
    "browser"     VARCHAR(100),
    "device_type" VARCHAR(50),
    "referrer"    TEXT,
    "user_agent"  TEXT
);

CREATE INDEX idx_click_logs_url ON "click_logs"("url_id");
CREATE INDEX idx_click_logs_date ON "click_logs"("clicked_at");
CREATE INDEX idx_click_logs_url_date ON "click_logs"("url_id", "clicked_at");

CREATE TABLE daily_url_stats (
    "url_id"       BIGINT NOT NULL REFERENCES "urls"("id") ON DELETE CASCADE,
    "stat_date"    DATE NOT NULL,
    "total_clicks" BIGINT DEFAULT 0,
    PRIMARY KEY ("url_id", "stat_date")
);

CREATE TABLE audit_logs (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "actor_user_id"   BIGINT REFERENCES "users"("id") ON DELETE SET NULL,
    "action"          VARCHAR(100) NOT NULL,
    "entity_type"     VARCHAR(50),
    "entity_id"       BIGINT,
    "metadata"         JSONB,
    "created_at"      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_audit_logs_created ON "admin_audit_log" ("created_at" DESC);
CREATE INDEX idx_audit_logs_actor ON "admin_audit_log" ("admin_id");

-- +goose Down

DROP TABLE IF EXISTS "audit_logs";
DROP TABLE IF EXISTS "daily_url_stats";
DROP TABLE IF EXISTS "click_logs";
DROP TABLE IF EXISTS "url_versions";
DROP TABLE IF EXISTS "urls";
DROP TABLE IF EXISTS "destinations";
DROP TABLE IF EXISTS "blocked_ip_ranges";
DROP TABLE IF EXISTS "blocked_domains";
DROP TABLE IF EXISTS "password_history";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "users";
