-- +goose Up

-- Add password_changed_at to users table for tracking password age
ALTER TABLE users ADD COLUMN password_changed_at TIMESTAMPTZ DEFAULT NOW();

-- Create password_history table to prevent password reuse
CREATE TABLE password_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    password_hash   VARCHAR(255) NOT NULL,
    ip_address      INET,
    user_agent      TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_password_history_user ON password_history(user_id);

-- +goose Down

DROP TABLE IF EXISTS password_history;
ALTER TABLE users DROP COLUMN IF EXISTS password_changed_at;